/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package br.com.ifba.smartwaste.view;

import java.awt.Frame;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author pc
 */
public class TelaCadastroPonto extends javax.swing.JDialog {

    /**
     * Creates new form TelaCadastroPonto
     */
    public TelaCadastroPonto(Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    public JButton getBtnCriar() {
        return btnCriar;
    }

    public JButton getBtnFechar() {
        return btnFechar;
    }


    public JTextArea getTxtEndereco() {
        return txtEndereco;
    }

    public JTextField getTxtSensorMetal() {
        return txtSensorMetal;
    }

    public JCheckBox getjCheckNAddMetal() {
        return jCheckNAddMetal;
    }

    public JCheckBox getjCheckNAddOrganico() {
        return jCheckNAddOrganico;
    }

    public JCheckBox getjCheckNAddPapel() {
        return jCheckNAddPapel;
    }

    public JCheckBox getjCheckNAddPlastico() {
        return jCheckNAddPlastico;
    }

    public JCheckBox getjCheckNAddVidro() {
        return jCheckNAddVidro;
    }

    public JTextField getTxtSensorOrganico() {
        return txtSensorOrganico;
    }

    public JTextField getTxtSensorPapel() {
        return txtSensorPapel;
    }

    public JTextField getTxtSensorPlastico() {
        return txtSensorPlastico;
    }

    public JTextField getTxtSensorVidro() {
        return txtSensorVidro;
    }

    public JTextField getTxtTamanhoMetal() {
        return txtTamanhoMetal;
    }

    public JTextField getTxtTamanhoOrganico() {
        return txtTamanhoOrganico;
    }

    public JTextField getTxtTamanhoPapel() {
        return txtTamanhoPapel;
    }

    public JTextField getTxtTamanhoPlastico() {
        return txtTamanhoPlastico;
    }

    public JTextField getTxtTamanhoVidro() {
        return txtTamanhoVidro;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        lblEndereco = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        btnFechar = new javax.swing.JButton();
        btnCriar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtEndereco = new javax.swing.JTextArea();
        jTabbedPaneLixeiras = new javax.swing.JTabbedPane();
        jPanelMetal = new javax.swing.JPanel();
        txtSensorMetal = new javax.swing.JTextField();
        lblTamanhoMetal = new javax.swing.JLabel();
        txtTamanhoMetal = new javax.swing.JTextField();
        lblSensorMetal = new javax.swing.JLabel();
        jCheckNAddMetal = new javax.swing.JCheckBox();
        jPanelOrganico = new javax.swing.JPanel();
        txtSensorOrganico = new javax.swing.JTextField();
        lblTamanhoOrganico = new javax.swing.JLabel();
        txtTamanhoOrganico = new javax.swing.JTextField();
        lblSensorOrganico = new javax.swing.JLabel();
        jCheckNAddOrganico = new javax.swing.JCheckBox();
        jPanelPapel = new javax.swing.JPanel();
        txtSensorPapel = new javax.swing.JTextField();
        lblTamanhoPapel = new javax.swing.JLabel();
        txtTamanhoPapel = new javax.swing.JTextField();
        lblSensorPapel = new javax.swing.JLabel();
        jCheckNAddPapel = new javax.swing.JCheckBox();
        jPanelPlastico = new javax.swing.JPanel();
        txtSensorPlastico = new javax.swing.JTextField();
        lblTamanhoPlastico = new javax.swing.JLabel();
        txtTamanhoPlastico = new javax.swing.JTextField();
        lblSensorPlastico = new javax.swing.JLabel();
        jCheckNAddPlastico = new javax.swing.JCheckBox();
        jPanelVidro = new javax.swing.JPanel();
        txtSensorVidro = new javax.swing.JTextField();
        lblTamanhoVidro = new javax.swing.JLabel();
        txtTamanhoVidro = new javax.swing.JTextField();
        lblSensorVidro = new javax.swing.JLabel();
        jCheckNAddVidro = new javax.swing.JCheckBox();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEndereco.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblEndereco.setText("Endereço:");

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitulo.setText("Criar novo ponto");

        btnFechar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        btnCriar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCriar.setText("Criar");

        txtEndereco.setColumns(20);
        txtEndereco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEndereco.setRows(5);
        jScrollPane1.setViewportView(txtEndereco);

        jTabbedPaneLixeiras.setToolTipText("");
        jTabbedPaneLixeiras.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtSensorMetal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblTamanhoMetal.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblTamanhoMetal.setText("Tamanho:");

        lblSensorMetal.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblSensorMetal.setText("ID do sensor:");

        jCheckNAddMetal.setText("Não adicionar");

        javax.swing.GroupLayout jPanelMetalLayout = new javax.swing.GroupLayout(jPanelMetal);
        jPanelMetal.setLayout(jPanelMetalLayout);
        jPanelMetalLayout.setHorizontalGroup(
            jPanelMetalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMetalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMetalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSensorMetal)
                    .addComponent(lblTamanhoMetal))
                .addGap(18, 18, 18)
                .addGroup(jPanelMetalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMetalLayout.createSequentialGroup()
                        .addComponent(jCheckNAddMetal)
                        .addGap(0, 110, Short.MAX_VALUE))
                    .addComponent(txtTamanhoMetal, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtSensorMetal, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanelMetalLayout.setVerticalGroup(
            jPanelMetalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMetalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMetalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTamanhoMetal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTamanhoMetal))
                .addGap(18, 18, 18)
                .addGroup(jPanelMetalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSensorMetal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSensorMetal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckNAddMetal)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jTabbedPaneLixeiras.addTab("Metal", jPanelMetal);

        txtSensorOrganico.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblTamanhoOrganico.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblTamanhoOrganico.setText("Tamanho:");

        lblSensorOrganico.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblSensorOrganico.setText("ID do sensor:");

        jCheckNAddOrganico.setText("Não adicionar");

        javax.swing.GroupLayout jPanelOrganicoLayout = new javax.swing.GroupLayout(jPanelOrganico);
        jPanelOrganico.setLayout(jPanelOrganicoLayout);
        jPanelOrganicoLayout.setHorizontalGroup(
            jPanelOrganicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOrganicoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOrganicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSensorOrganico)
                    .addComponent(lblTamanhoOrganico))
                .addGap(18, 18, 18)
                .addGroup(jPanelOrganicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelOrganicoLayout.createSequentialGroup()
                        .addComponent(jCheckNAddOrganico)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtTamanhoOrganico, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                    .addComponent(txtSensorOrganico, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanelOrganicoLayout.setVerticalGroup(
            jPanelOrganicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelOrganicoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOrganicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTamanhoOrganico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTamanhoOrganico))
                .addGap(18, 18, 18)
                .addGroup(jPanelOrganicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSensorOrganico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSensorOrganico))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckNAddOrganico)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jTabbedPaneLixeiras.addTab("Organico", jPanelOrganico);

        txtSensorPapel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblTamanhoPapel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblTamanhoPapel.setText("Tamanho:");

        lblSensorPapel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblSensorPapel.setText("ID do sensor:");

        jCheckNAddPapel.setText("Não adicionar");

        javax.swing.GroupLayout jPanelPapelLayout = new javax.swing.GroupLayout(jPanelPapel);
        jPanelPapel.setLayout(jPanelPapelLayout);
        jPanelPapelLayout.setHorizontalGroup(
            jPanelPapelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPapelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPapelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSensorPapel)
                    .addComponent(lblTamanhoPapel))
                .addGap(18, 18, 18)
                .addGroup(jPanelPapelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPapelLayout.createSequentialGroup()
                        .addComponent(jCheckNAddPapel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtTamanhoPapel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                    .addComponent(txtSensorPapel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanelPapelLayout.setVerticalGroup(
            jPanelPapelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPapelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPapelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTamanhoPapel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTamanhoPapel))
                .addGap(18, 18, 18)
                .addGroup(jPanelPapelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSensorPapel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSensorPapel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckNAddPapel)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jTabbedPaneLixeiras.addTab("Papel", jPanelPapel);

        txtSensorPlastico.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblTamanhoPlastico.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblTamanhoPlastico.setText("Tamanho:");

        lblSensorPlastico.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblSensorPlastico.setText("ID do sensor:");

        jCheckNAddPlastico.setText("Não adicionar");

        javax.swing.GroupLayout jPanelPlasticoLayout = new javax.swing.GroupLayout(jPanelPlastico);
        jPanelPlastico.setLayout(jPanelPlasticoLayout);
        jPanelPlasticoLayout.setHorizontalGroup(
            jPanelPlasticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPlasticoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPlasticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSensorPlastico)
                    .addComponent(lblTamanhoPlastico))
                .addGap(18, 18, 18)
                .addGroup(jPanelPlasticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPlasticoLayout.createSequentialGroup()
                        .addComponent(jCheckNAddPlastico)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtTamanhoPlastico, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                    .addComponent(txtSensorPlastico, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanelPlasticoLayout.setVerticalGroup(
            jPanelPlasticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPlasticoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPlasticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTamanhoPlastico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTamanhoPlastico))
                .addGap(18, 18, 18)
                .addGroup(jPanelPlasticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSensorPlastico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSensorPlastico))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckNAddPlastico)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jTabbedPaneLixeiras.addTab("Plastico", jPanelPlastico);

        txtSensorVidro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblTamanhoVidro.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblTamanhoVidro.setText("Tamanho:");

        lblSensorVidro.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblSensorVidro.setText("ID do sensor:");

        jCheckNAddVidro.setText("Não adicionar");

        javax.swing.GroupLayout jPanelVidroLayout = new javax.swing.GroupLayout(jPanelVidro);
        jPanelVidro.setLayout(jPanelVidroLayout);
        jPanelVidroLayout.setHorizontalGroup(
            jPanelVidroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVidroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelVidroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSensorVidro)
                    .addComponent(lblTamanhoVidro))
                .addGap(18, 18, 18)
                .addGroup(jPanelVidroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelVidroLayout.createSequentialGroup()
                        .addComponent(jCheckNAddVidro)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtTamanhoVidro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                    .addComponent(txtSensorVidro, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanelVidroLayout.setVerticalGroup(
            jPanelVidroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelVidroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelVidroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTamanhoVidro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTamanhoVidro))
                .addGap(18, 18, 18)
                .addGroup(jPanelVidroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSensorVidro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSensorVidro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckNAddVidro)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jTabbedPaneLixeiras.addTab("Vidro", jPanelVidro);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(124, 124, 124))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnFechar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCriar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblEndereco)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTabbedPaneLixeiras))
                        .addGap(0, 37, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEndereco)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPaneLixeiras, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFechar)
                    .addComponent(btnCriar))
                .addGap(17, 17, 17))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFecharActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroPonto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroPonto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroPonto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroPonto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaCadastroPonto dialog = new TelaCadastroPonto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCriar;
    private javax.swing.JButton btnFechar;
    private javax.swing.JCheckBox jCheckNAddMetal;
    private javax.swing.JCheckBox jCheckNAddOrganico;
    private javax.swing.JCheckBox jCheckNAddPapel;
    private javax.swing.JCheckBox jCheckNAddPlastico;
    private javax.swing.JCheckBox jCheckNAddVidro;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelMetal;
    private javax.swing.JPanel jPanelOrganico;
    private javax.swing.JPanel jPanelPapel;
    private javax.swing.JPanel jPanelPlastico;
    private javax.swing.JPanel jPanelVidro;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPaneLixeiras;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblSensorMetal;
    private javax.swing.JLabel lblSensorOrganico;
    private javax.swing.JLabel lblSensorPapel;
    private javax.swing.JLabel lblSensorPlastico;
    private javax.swing.JLabel lblSensorVidro;
    private javax.swing.JLabel lblTamanhoMetal;
    private javax.swing.JLabel lblTamanhoOrganico;
    private javax.swing.JLabel lblTamanhoPapel;
    private javax.swing.JLabel lblTamanhoPlastico;
    private javax.swing.JLabel lblTamanhoVidro;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextArea txtEndereco;
    private javax.swing.JTextField txtSensorMetal;
    private javax.swing.JTextField txtSensorOrganico;
    private javax.swing.JTextField txtSensorPapel;
    private javax.swing.JTextField txtSensorPlastico;
    private javax.swing.JTextField txtSensorVidro;
    private javax.swing.JTextField txtTamanhoMetal;
    private javax.swing.JTextField txtTamanhoOrganico;
    private javax.swing.JTextField txtTamanhoPapel;
    private javax.swing.JTextField txtTamanhoPlastico;
    private javax.swing.JTextField txtTamanhoVidro;
    // End of variables declaration//GEN-END:variables
}
